# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "94b133d6355fcded54f94b78191581a7"
name = "Chatlivo-test-2"
application_url = "https://example.com"
embedded = true

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_metaobject_definitions,write_metaobjects,write_products"

[auth]
redirect_urls = [ "https://example.com/api/auth" ]

[webhooks]
api_version = "2026-10"
