name: Deploy to production Server

on:
  push:
    branches:
      - main

jobs:
  deploy:
    name: Build & Deploy via SSH
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      - name: Install dependencies
        run: npm ci

      - name: Deploy entire project
        uses: burnett01/rsync-deployments@7.0.1
        with:
          switches: -avzr --delete --exclude=node_modules --exclude=.git --exclude=.env.local --exclude=build
          path: ./
          remote_path: /var/www/shopify.chatlivo.com
          remote_host: ${{ secrets.SERVER_HOST }}
          remote_user: ${{ secrets.SERVER_USER }}
          remote_key: ${{ secrets.SERVER_SSH_KEY }}
          remote_port: 22
          legacy_allow_rsa_hostkeys: true

      - name: Build and run on server
        uses: appleboy/ssh-action@v1
        with:
          host: ${{ secrets.SERVER_HOST }}
          username: ${{ secrets.SERVER_USER }}
          key: ${{ secrets.SERVER_SSH_KEY }}
          port: 22
          script: |
            cd /var/www/shopify.chatlivo.com
            npm install
            # npm run setup
            npm run build
            pm2 restart shopify-chatlivo --update-env || pm2 start npm --name shopify-chatlivo -- start
            echo "Deployment complete!"
